### ISSUE TITLE
Timeout for nvidia-persistenced too short for multi-GPU?

### ISSUE THREAD

**Issue by nguyenlienviet** [NVIDIA/nvrc#159]
When trying a kata pod with 4+ B200 GPUs with TDX, I saw the pod got stuck in ContainerCreating. I enabled kata debug log and found:
```
[    6.844792] nvidia-nvlink: Nvlink Core is being initialized, major device number 243"
[    6.845313] "
[    6.853506] probe of 0000:02:00.0 returned 0 after 2980 usecs"
[    6.858014] probe of 0000:03:00.0 returned 0 after 4103 usecs"
[    6.862285] probe of 0000:04:00.0 returned 0 after 3878 usecs"
[    6.865451] probe of 0000:05:00.0 returned 0 after 2860 usecs"
[    6.865832] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  590.48.01  Release Build  (@a71a57ba69b1)  Sat Apr 18 10:33:23 UTC 2026"
[    6.866101] initcall nvidia_init_module+0x0/0x760 [nvidia] returned 0 after 21559 usecs"
[    6.904511] calling  uvm_init_entry+0x0/0x1000 [nvidia_uvm] @ 251"
[    6.906114] initcall uvm_init_entry+0x0/0x1000 [nvidia_uvm] returned 0 after 1179 usecs"
[    7.043922] NVRM: GPU0 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS"
[    7.093285] ACPI Warning: \\_SB.PCI0.S28.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)"
[    9.609486] NVRM: GPU0 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU"
[   10.572652] calling  nvkms_init+0x0/0x1000 [nvidia_modeset] @ 279"
[   10.574667] nvidia-modeset: Loading NVIDIA UNIX Open Kernel Mode Setting Driver for x86_64  590.48.01  Release Build  (@a71a57ba69b1)  Sat Apr 18 10:32:21 UTC 2026"
[   10.575031] initcall nvkms_init+0x0/0x1000 [nvidia_modeset] returned 0 after 1932 usecs"
[   41.930874] NVRM: GPU1 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS"
[   41.959802] ACPI Warning: \\_SB.PCI0.S30.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)"
[   44.710177] NVRM: GPU1 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU"
[   75.782146] NVRM: GPU2 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS"
[   75.809692] ACPI Warning: \\_SB.PCI0.S38.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)"
[   78.498206] NVRM: GPU2 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU"
[  109.802092] NVRM: GPU3 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS"
[  109.829000] ACPI Warning: \\_SB.PCI0.S40.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)"
[  112.636796] NVRM: GPU3 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU"
panic: panicked at src/kmsg.rs:95:13:"
timeout waiting for: Local RPC services initialized"
```
The timeout is only 120s: https://github.com/NVIDIA/nvrc/blob/f6f5c0c5da927cb132e87088eff054106ef52202/src/daemon.rs#L52 and GPU3 was only initialized at 112.6s. I had tried the same setup with 3 GPUs and the pod creation succeeded, so I think this timeout is the only blocker. Can we make it variable based on number of GPUs?

**Comment by zvonkok** [comment]
Hmm, interesting. I've tested this with an 8x GPU on a B200, so I am curious, can you add the following to 

```
kernel_params=" .... nvrc.log=debug" 
```
and share the kernel messages?

**Comment by nguyenlienviet** [comment]
Thanks for the reply! Here it is (note this time I'm attaching 8x B200):
```
...
[    6.965284] NVRC::kernel_params[1]: nvrc.log: DEBUG
[    6.967686] NVRC::mode[1]: topology: 8 GPU, 0 NVSWITCH, 0 PCI_SW_MNG
[    6.968050] NVRC::mode[1]: mode: gpu 8 GPU
[    6.968783] NVRC::execute[1]: /sbin/modprobe nvidia
[    7.071096] nvidia: loading out-of-tree module taints kernel.
[    7.079861] calling  nvidia_init_module+0x0/0x760 [nvidia] @ 233
[    7.080528] nvidia-nvlink: Nvlink Core is being initialized, major device number 243
[    7.080700]
[    7.088215] probe of 0000:02:00.0 returned 0 after 2752 usecs
[    7.091150] probe of 0000:03:00.0 returned 0 after 2572 usecs
[    7.094058] probe of 0000:04:00.0 returned 0 after 2603 usecs
[    7.096779] probe of 0000:05:00.0 returned 0 after 2387 usecs
[    7.099797] probe of 0000:06:00.0 returned 0 after 2731 usecs
[    7.102870] probe of 0000:07:00.0 returned 0 after 2750 usecs
[    7.105949] probe of 0000:08:00.0 returned 0 after 2803 usecs
[    7.109010] probe of 0000:09:00.0 returned 0 after 2695 usecs
[    7.109407] NVRM: loading NVIDIA UNIX Open Kernel Module for x86_64  590.48.01  Release Build  (@a71a57ba69b1)  Sat Apr 18 10:33:23 UTC 2026
[    7.110066] initcall nvidia_init_module+0x0/0x760 [nvidia] returned 0 after 29775 usecs
[    7.111274] NVRC::execute[1]: /sbin/modprobe nvidia-uvm
[    7.146300] calling  uvm_init_entry+0x0/0x1000 [nvidia_uvm] @ 250
[    7.148395] initcall uvm_init_entry+0x0/0x1000 [nvidia_uvm] returned 0 after 1858 usecs
[    7.149468] NVRC::execute[1]: /bin/nvidia-persistenced --verbose --uvm-persistence-mode
[    7.284431] NVRM: GPU0 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS
[    7.347472] ACPI Warning: \\_SB.PCI0.S28.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)
[    7.653641] NVRC::syslog[1]: May 28 21:20:13 nvidia-persistenced: Verbose syslog connection opened
[    7.654390] NVRC::syslog[1]: May 28 21:20:13 nvidia-persistenced: Directory /var/run/nvidia-persistenced will not be removed on exit
[    7.659658] NVRC::syslog[1]: May 28 21:20:13 nvidia-persistenced: Started (256)
[    7.660065] NVRC::syslog[1]: May 28 21:20:13 nvidia-persistenced: device 0000:02:00.0 - registered
[    9.892448] NVRM: GPU0 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU
[   10.846810] calling  nvkms_init+0x0/0x1000 [nvidia_modeset] @ 283
[   10.848527] nvidia-modeset: Loading NVIDIA UNIX Open Kernel Mode Setting Driver for x86_64  590.48.01  Release Build  (@a71a57ba69b1)  Sat Apr 18 10:32:21 UTC 2026
[   10.849096] initcall nvkms_init+0x0/0x1000 [nvidia_modeset] returned 0 after 1825 usecs
[   41.113568] NVRM: GPU1 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS
[   41.145766] ACPI Warning: \\_SB.PCI0.S30.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)
[   41.189700] NVRC::syslog[1]: May 28 21:20:47 nvidia-persistenced: device 0000:02:00.0 - Could not Enable UVM Persistence mode becausethe NVLink fabric is not ready: 0x81
[   41.201713] NVRC::syslog[1]: May 28 21:20:47 nvidia-persistenced: device 0000:02:00.0 - persistence mode enabled.
[   41.202305] NVRC::syslog[1]: May 28 21:20:47 nvidia-persistenced: device 0000:02:00.0 - NUMA memory onlined.
[   41.202570] NVRC::syslog[1]: May 28 21:20:47 nvidia-persistenced: device 0000:03:00.0 - registered
[   44.010812] NVRM: GPU1 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU
[   76.231370] NVRC::syslog[1]: May 28 21:21:22 nvidia-persistenced: device 0000:03:00.0 - Could not Enable UVM Persistence mode becausethe NVLink fabric is not ready: 0x81
[   76.233874] NVRC::syslog[1]: May 28 21:21:22 nvidia-persistenced: device 0000:03:00.0 - persistence mode enabled.
[   76.234348] NVRC::syslog[1]: May 28 21:21:22 nvidia-persistenced: device 0000:03:00.0 - NUMA memory onlined.
[   76.234879] NVRC::syslog[1]: May 28 21:21:22 nvidia-persistenced: device 0000:04:00.0 - registered
[   76.262313] NVRM: GPU2 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS
[   76.295134] ACPI Warning: \\_SB.PCI0.S38.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)
[   79.096573] NVRM: GPU2 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU
[  110.315528] NVRM: GPU3 kbifCacheVFInfo_GB100: Unable to read NV_PF0_INITIAL_AND_TOTAL_VFS
[  110.346140] ACPI Warning: \\_SB.PCI0.S40.S00._DSM: Argument #4 type mismatch - Found [Buffer], ACPI requires [Package] (20250807/nsarguments-61)
[  110.766861] NVRC::syslog[1]: May 28 21:21:56 nvidia-persistenced: device 0000:04:00.0 - Could not Enable UVM Persistence mode becausethe NVLink fabric is not ready: 0x81
[  110.767789] NVRC::syslog[1]: May 28 21:21:56 nvidia-persistenced: device 0000:04:00.0 - persistence mode enabled.
[  110.768445] NVRC::syslog[1]: May 28 21:21:56 nvidia-persistenced: device 0000:04:00.0 - NUMA memory onlined.
[  110.768919] NVRC::syslog[1]: May 28 21:21:56 nvidia-persistenced: device 0000:05:00.0 - registered
[  113.161615] NVRM: GPU3 knvlinkIsNvleEnabled_GB100: CC and Nvlink encryption features are enabled on the GPU
panic: panicked at src/kmsg.rs:95:13:
timeout waiting for: Local RPC services initialized
[  127.289090] serial8250 serial8250: shutdown
[  127.289421] virtio_net virtio4: shutdown
[  127.322648] vmw_vsock_virtio_transport virtio3: shutdown
[  127.324057] virtio_scsi virtio2: shutdown
[  127.327246] virtio_blk virtio1: shutdown
[  127.328827] virtio_console virtio0: shutdown
```

**Comment by yunbo-xufeng** [comment]
I also met the same issue on TDX+4 or 8 H20 passthrough，1 and 2 H20 passthrough is ok。

**Comment by zvonkok** [comment]
`Could not Enable UVM Persistence mode becausethe NVLink fabric is no` Do you have the fabric-manager running on the host? 

Using one GPU on the HGX you do not need the fabricmanager. Using 2 GPUs, you need an NVLink partition. For 8 GPUs the default NVLINK partition is 8 GPUs with the fabricmanager running.

**Comment by zvonkok** [comment]
Lets first clarify what you want to run and how. What is the virtualization model you're using? How are you managing the NVLINK partitions? 

Looking at the output, the code behavior appears correct; NVRC times out because NVFabric is not initialized.

**Comment by pamanseau** [comment]
## Update: NVRC timeout + PPCIE GPU Ready State (full root cause)

We've now fully diagnosed and resolved the CUDA Error 802 (`system not yet initialized`) on HGX H200 (8× H200 + Intel TDX) in PPCIE CC mode. There are **three** separate issues that all contribute:

### 1. NVRC 120s timeout (this issue, nvrc#159)
The hardcoded 120s timeout for `nvidia-persistenced`'s "Local RPC services initialized" marker is too short for 8× H200 in PPCIE/TDX mode. We patched `daemon.rs` to 600s. This fixes the VM panic but is NOT sufficient alone.

### 2. NVSwitch VFIO passthrough (kata-containers#13430)
The Kata runtime-rs shim's `filter_bridge_device` uses `IOMMU_IGNORE` (0x0600) which is a subset of 0x0680 — it wrongly strips NVSwitches (PCI class 0x0680) from the guest. We patched `core.rs` to add a `0x0680` exception. See https://github.com/kata-containers/kata-containers/issues/13430.

### 3. Missing `nvidia.com/nvswitch` resource request (root cause of CUDA 802)
Even with the patched shim, the NVSwitches were NOT visible inside the Kata guest. The root cause: **the pod spec did not request `nvidia.com/nvswitch` resources**. Without the resource request, the gpu-operator's sandbox device plugin doesn't pass the NVSwitches through to the guest.

Without NVSwitches in the guest:
- NSCQ (NVSwitch Control Query) init fails: `NSCQ_RC_WARNING: RDT init failure (Code 1)`
- NVSwitch attestation evidence can't be collected
- GPU attestation is incomplete
- `nvidia-smi conf-compute -srs 1` (Secure AI Ready State) fails silently
- GPU stays in `NotReady` → CUDA Error 802

**Fix:** Add `nvidia.com/nvswitch: "4"` to the pod's resource limits and requests:
```yaml
resources:
  limits:
    nvidia.com/GH100_H200_SXM_141GB: "8"
    nvidia.com/nvswitch: "4"  # REQUIRED on PPCIE nodes
```

**Verified:** Pod went from crash loop (CUDA 802 every restart) to `1/1 Running` serving inference requests on `am-h200-23` (HGX H200 + TDX).

### Summary of the fix chain
1. Patched NVRC: 120s → 600s timeout (this issue)
2. Patched Kata runtime-rs shim: `0x0680` NVSwitch exception (kata-containers#13430)
3. Added `nvidia.com/nvswitch: "4"` to pod resource requests ← **this was the key missing piece**

All three are required. Without #3, even with the patched NVRC and shim, the NVSwitches never reach the guest and CUDA can't initialize.

**Comment by pawelpros** [comment]
I was able to verify fix mentioned in PR#222 with B300 (NVIDIA B300 SXM6 AC	GPU1) and without additional changes it works fine (tested with Ubuntu 26.04.1 and Kata 4.1.0)
